apiVersion: apps/v1
kind: Deployment
metadata:
  name: connectsphere-platform-support
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connectsphere-platform-support
  template:
    metadata:
      labels:
        app: connectsphere-platform-support
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
          ports:
            - containerPort: 9200
