server:
  port: 8084

spring:
  application:
    name: like-service

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/connectsphere_like_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

logging:
  file:
    name: logs/like-service.log
